In [2]:
import numpy as np  # we should import numpy before use it in our code
from numpy import *

In [3]:
# conver a list into an array

arr = array([2,3,8,9,7])

print(arr)

[2 3 8 9 7]


In [4]:
print(arr.dtype)

int32


1 byte = 8 bit

for integer it takes 4 bytes in memory so it contain 8*4 = 32 bits

for float it takes 8 bytes in memory so it contain 8*8 = 64 bits

In [5]:
arr = array([2,3,8,9,7.5])   #if we have  at least one float number in list then the total array values converted into float

print(arr)
print(arr.dtype)

[2.  3.  8.  9.  7.5]
float64


In [9]:
arr = array([2,3,4,8,9,5.5], int)
print(arr)
print(arr.dtype)

[2 3 4 8 9 5]
int32


In [12]:
#arr = linspace(start, end, parts)  # linspace make an array between the start and end values by it desires parts.
arr = linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


### Numpy array using arrange

In [14]:
#arr = arange(start, end, step)  in here step is not mendatory
arr = np.arange(1,15)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
arr = np.arange(1,15,2)

print(arr)

[ 1  3  5  7  9 11 13]


### Numpy array using Logspace

In [20]:
arr = logspace(1,2,6)      # log102()  first value indicate base, second value indicate power of base, and third value indicates the number of values

print(arr)

[ 10.          15.84893192  25.11886432  39.81071706  63.09573445
 100.        ]


In [21]:
print(arr[1])

15.848931924611133


In [22]:
print('%.2f' %arr[1])

15.85


### Numpy array using Zeros

In [23]:
arr = zeros(5)  # by default all the values are float

print(arr)

[0. 0. 0. 0. 0.]


In [24]:
arr = zeros(5, int)

print(arr)

[0 0 0 0 0]


In [25]:
arr = zeros((4,3))   # (row, column)

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
arr = zeros((4,3),int)    # 2d array

print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
arr = zeros((4,3,2), int)   # 3d array   # first vale is how many two array it contains, sencond value is row and third value is column

print(arr)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


### Create numpy array from List

In [30]:
list = [1,2,3,4,5,6]

arr = np.array(list)

arr    # print without using print()

#print(arr)

array([1, 2, 3, 4, 5, 6])

In [34]:
list = [[1,2,3,4],[5,6,7,8]]  # if we want to convert a nested list into numpy array then all the dymension of each list should be same dymention

arr = np.array(list)

arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
list = [[1,2,3,4],[5,6,7]]

arr = np.array(list)

arr

array([list([1, 2, 3, 4]), list([5, 6, 7])], dtype=object)

In [60]:
matrix = np.full(5,10)

matrix

array([10, 10, 10, 10, 10])

In [36]:
matrix = np.full((4,3),10)  # 4 rows, 3 columns and each value is 10

matrix

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [37]:
matrix = np.eye(3)  # eye means identity metrix

# here the 1 ares called diagonal elements

matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
matrix = np.diag([4,5,6])

matrix

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

# Random Generation in Numpy

In [39]:
arr = np.random.rand(5)

arr

array([0.91585054, 0.13390073, 0.77804244, 0.08870681, 0.15297798])

In [40]:
arr = np.random.rand(3,4)

arr

array([[0.09947926, 0.51294349, 0.24558129, 0.47897397],
       [0.75122875, 0.29699549, 0.08333353, 0.54087481],
       [0.12646124, 0.94530978, 0.27847557, 0.72884856]])

In [41]:
arr = np.random.rand(3,4,3)

arr

array([[[0.94791735, 0.93585205, 0.73665367],
        [0.6749181 , 0.33113448, 0.72387079],
        [0.73964088, 0.50436839, 0.05007569],
        [0.48625027, 0.12983742, 0.11389619]],

       [[0.45981519, 0.23725873, 0.7240885 ],
        [0.97989206, 0.33781449, 0.45378124],
        [0.48881042, 0.82678266, 0.24801544],
        [0.76547279, 0.54604034, 0.51255812]],

       [[0.54940883, 0.01780336, 0.21022689],
        [0.76207414, 0.82009028, 0.86861574],
        [0.80102754, 0.60080991, 0.18044055],
        [0.9147367 , 0.2009149 , 0.95903439]]])

In [43]:
arr = np.random.randn(5)

arr

array([-0.24647567, -1.93068192,  0.98914489, -1.4287344 , -0.03345639])

In [45]:
arr = np.random.randint(0,10,15)

arr

array([9, 4, 4, 7, 5, 7, 6, 9, 6, 9, 6, 1, 5, 6, 5])

In [46]:
arr = np.random.randint(1,15,(4,4))

arr

array([[ 5,  8,  4,  4],
       [ 8,  7,  8,  9],
       [ 9, 10,  3, 11],
       [11,  6,  5,  1]])

# Some function in Numpy

In [49]:
arr1 = linspace(0,15,16)
print(arr1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [50]:
arr2 = ones((4,3),int)

print(arr2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [51]:
arr1.ndim

1

In [52]:
arr2.ndim

2

In [53]:
arr1.shape

(16,)

In [54]:
arr2.shape

(4, 3)

In [55]:
arr1.size

16

In [56]:
arr2.size

12

In [57]:
arr1.dtype

dtype('float64')

In [58]:
arr2.dtype

dtype('int32')

In [59]:
arr1.data

# Indexing in Numpy array

In [60]:
arr = linspace(0,15,16)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [61]:
for data in arr:
    print(data, end = " ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [62]:
for i in range(len(arr)):
    print(arr[i], end =" ")

0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0 13.0 14.0 15.0 

In [63]:
print(arr[0:5])

[0. 1. 2. 3. 4.]


In [64]:
print(arr[:6])

[0. 1. 2. 3. 4. 5.]


In [65]:
print(arr[4:])

[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [66]:
arr1 = arr[5:]

print(arr1)

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [67]:
arr2 = arr1.copy

arr2

<function ndarray.copy>

In [68]:
print(arr2)

<built-in method copy of numpy.ndarray object at 0x0000019395597990>


# Array selection in Numpy

In [71]:
arr = np.random.randint(1,15,(6,5))

arr

array([[ 9, 14,  6,  1,  1],
       [ 6,  7,  8,  7, 13],
       [ 2, 14, 13, 14, 14],
       [ 6, 11, 14,  6,  4],
       [ 9,  5, 10, 13, 13],
       [ 7,  4, 13,  3, 11]])

In [70]:
a1 = arr[0:4, 0:3]
a1

array([[ 9, 11,  5],
       [ 9, 11,  3],
       [ 6,  4, 13],
       [ 9, 12, 13]])

In [72]:
a2 = arr[4:,]
a2

array([[ 9,  5, 10, 13, 13],
       [ 7,  4, 13,  3, 11]])

In [73]:
a3 = arr[3:5, 2:4]
a3

array([[14,  6],
       [10, 13]])

In [74]:
bool_m = a1>6

bool_m

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

# Reshape and Ravel function

In [124]:
a1 = arr[0:4, 0:3]
a1

array([[ 4, 10, 14],
       [ 9, 12, 12],
       [12,  8, 11],
       [ 4, 12,  6]])

In [125]:
a1.shape

(4, 3)

In [126]:
arr1 = a1.reshape(3,4)
arr1

array([[ 4, 10, 14,  9],
       [12, 12, 12,  8],
       [11,  4, 12,  6]])

In [129]:
arr2 = a1.reshape(6,2)
arr2

array([[ 4, 10],
       [14,  9],
       [12, 12],
       [12,  8],
       [11,  4],
       [12,  6]])

In [130]:
arr3 = arr1.ravel()
arr3

array([ 4, 10, 14,  9, 12, 12, 12,  8, 11,  4, 12,  6])

# Arithmetic Operation in Numpy

In [131]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [133]:
print(arr-arr)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [134]:
print(arr*arr)

[  1   4   9  16  25  36  49  64  81 100 121 144]


In [135]:
print(arr/arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [137]:
arr = np.arange(0,13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [138]:
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Moon PC\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [139]:
arr1 = a1.reshape(3,4)
arr1

array([[ 4, 10, 14,  9],
       [12, 12, 12,  8],
       [11,  4, 12,  6]])

In [140]:
arr2 = a1.reshape(6,2)
arr2

array([[ 4, 10],
       [14,  9],
       [12, 12],
       [12,  8],
       [11,  4],
       [12,  6]])

In [143]:
arr3 = arr1+arr2.reshape(3,4)
arr3

array([[ 8, 20, 28, 18],
       [24, 24, 24, 16],
       [22,  8, 24, 12]])

In [144]:
arr3.sum(axis=0)

array([54, 52, 76, 46])

In [145]:
arr3.sum(axis=1)

array([74, 88, 66])