In [10]:
import numpy as np
row_vec = np.array([7, 2, 9, 8]).reshape(2, 2)

In [11]:
print(row_vec)

[[7 2]
 [9 8]]


In [12]:
row_vec.shape

(2, 2)

In [13]:
mat = np.array([[2, 0], [5, 1], [7, -3]])


In [14]:
mat

array([[ 2,  0],
       [ 5,  1],
       [ 7, -3]])

In [15]:
mat.shape

(3, 2)

In [18]:
x = mat.reshape(2,3)

In [19]:
x

array([[ 2,  0,  5],
       [ 1,  7, -3]])

In [20]:
x[1,2]

-3

In [21]:
x[0,0]

2

In [24]:
a = np.arange(4).reshape(2,2)

In [25]:
a

array([[0, 1],
       [2, 3]])

In [26]:
import numpy as np

# row vector of the integers 1 to 6, inclusive
row_vector = np.array([1,2,3,4,5,6])

# column vector of the integers 11 to 14, inclusive
column_vector = np.array([11,12,13,14])

In [27]:
row_vector

array([1, 2, 3, 4, 5, 6])

In [30]:
import numpy as np

# row vector of the integers 1 to 6, inclusive
row_vector = np.arange(1,7)

# column vector of the integers 11 to 14, inclusive
column_vector = np.arange(11,15)

In [31]:
row_vector

array([1, 2, 3, 4, 5, 6])

In [40]:
import numpy as np

def elements_greater_than_mean(arr):
    '''
    Return a new array with the elements of the array
    arr that are greater than its mean.

    >>> elements_greater_than_mean(np.array([0.2, 0.8, 0.3, 0.6]))
    array([0.8, 0.6])
    '''
    m = np.mean(arr)
    
    return(arr[arr>m])
    
arr=np.array([1,2,3,4,5,6])
print(elements_greater_than_mean(arr))

[4 5 6]


In [41]:
import numpy as np


def dot_product(a, b):
    '''
    Return the dot product of two numpy arrays of the same length.

    Parameters
    ----------
    a: numpy array with shape (n, )
        An array of floating point numbers.
    b: numpy array with shape (n, )
        An array of floating point numbers.

    Returns
    -------
    dot_prod: float
        The dot product of a and b.

    '''
    a = a*b
    b = np.sum(a)
    return(b)
    
a = np.array([1,2,3])
b = np.array([2,4,5])

print(dot_product(a, b))

25


In [46]:
import numpy as np


def mat_inner_product(X, Y):
    '''
    Multiply two numpy arrays, if possible.

    Parameters
    ----------
    X: array, shape (n, m)
    Y: array, shape (p, q)

    Returns
    -------
    ret: array, shape (n, q), or False
        If the two arrays cannot be multiplied (X times Y), then return False.
        Otherwise return the product.
    '''
    m = X.shape[1]
    p = Y.shape[0]
    if(m==p):    
        return(X.dot(Y))
    else:
        return(False)
X = np.array([[3,2],[7,4],[9,1]])
Y = np.array([[2, -1, 3, 0], [-2, 0, -1, 4],[2, -1, 3, 0]])

print(mat_inner_product(X, Y))

False


In [49]:
import numpy as np

def elements_twice_min(arr):
    """
    Return all elements of array arr that are greater than or equal to 2 times
    the minimum element of arr.

    Parameters
    ----------
    arr: NumPy array (n, m)

    Returns
    -------
    NumPy Array, a vector of size between: 0 and (n * m) - 1
    """
    m = np.min(arr)
    return(arr[arr>=2*m])
    
    
arr = np.array([1,2,3,4,5,6,5,4])
print(elements_twice_min(arr))

[2 3 4 5 6 5 4]


In [52]:
import numpy as np

def mat_addition(A, B):
    """
    Add vector/matrix arrays A and B together. If they cannot be added
    return False.

    Parameters
    ----------
    A: NumPy array size of (n,) or (n, m)
    B: NumPy array size of (p,) or (p, q)

    Returns
    -------
    NumPy Array of same size as A and B, or False if their sizes differ.
    """
    x = np.size(A)
    y = np.size(B)
    if(x==y):
        return(A+B)
    else:
        return(False)
    
A = np.array([1,2,3])
B = np.array([2,4,6])
print(mat_addition(A,B))

False


In [59]:
import numpy as np

def xtx_product(X):
    """
    Given a matrix X, calculate the inner product X^T X, where the ^T
    operator denotes the transpose.

    Parameters
    ----------
    X: NumPy array size of (n, m)

    Returns
    -------
    NumPy Array of size (m, m)
    """
    XT = np.transpose(X)
     
    return(XT.dot(X))
    
    

X = np.array([[1,2,4],[3,4,3]])

print(xtx_product(X))

[[10 14 13]
 [14 20 20]
 [13 20 25]]


In [63]:
import numpy as np

def mat_rank(X):
    """
    Given a matrix X, return its rank.

    Parameters
    ----------
    X: NumPy array size of (n, m)

    Returns
    -------
    (int) the rank of X
    """
    m = np.linalg.matrix_rank(X)
    return(m)

X = np.array([[1,1,1,1],[1,2,3,4,5],[6,7,8,9,10],[2,4,6,8,10]])
print(mat_rank(X))

1


In [64]:
import numpy as np

def elements_greater_than_mean(arr):
    '''
    Return a new array with the elements of the array
    arr that are greater than its mean.

    >>> elements_greater_than_mean(np.array([0.2, 0.8, 0.3, 0.6]))
    array([0.8, 0.6])
    '''
    m = np.mean(arr)
    
    return(arr[arr>m])
    
arr=np.array([1,2,3,4,5,6])
print(elements_greater_than_mean(arr))

[4 5 6]
